# Generated by Django 3.0.8 on 2021-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_one', models.TextField()),
                ('paragraph_two', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfoliopiece',
            name='image',
            field=models.ImageField(upload_to='static/assets/portfolio-images'),
        ),
    ]
