# Generated by Django 3.2.6 on 2021-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210820_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcopy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliopiece',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfoliopiece',
            name='image',
            field=models.ImageField(upload_to='media/static/assets/portfolio-images'),
        ),
    ]
